### ISSUE TITLE
UI.Card() returns ReferenceError: Symbol is not defined

### ISSUE THREAD

**Issue by clach04** [hiway/pybble#18]
When running compiled app in local SDK 4.3 emulator and attempting to create a Card from UI get:

	ReferenceError: Symbol is not defined
	    at dict (app.js:1862:36)
	    at Object.Card (app.js:2399:20)
	    at app.js:2628:17
	    at console_card_platform_hello (app.js:2644:5)
	    at Object.loader (app.js:2647:1)
	    at Object.loader.require (loader.js:44:10)
	    at require (loader.js:41:48)
	    at Pebble.<anonymous> (main.js:41:3)

* The issue occurs where Symbol.interator is used (an ES6 feature? definitely from 2013 spec). Looks like pypkjs, Python implementation of PebbleKit JS. which includes PyV8 is likely an older js engine version
* Does NOT occur on Android phone, Pebble app appears to have a later JS implementation?

No real workaround (as Transcrypt 3.6.x appear to require this). As CloudPebble.net is no longer available unclear how that worked. Not looked in to self-hosted (or alternatives cloud pebble instances).

Seen with:

* Transcrypt 3.5.213 - 2016-08-19 about the time of this project
* Transcrypt 3.5.217 released 2016-08-26

**Comment by clach04** [comment]
@hiway  this is a bit of a big ask, as well as along shot ;-) Do you by any chance recall the version of Transcrypt you used when you last played with this?

If not, is there any chance you have generated app.js file(s) laying around that you could attach to this ticket so I and peek inside and try and figure out the version? Rather than me randomly trying older versions of Transcrypt.

Other option would be to try Skulpt, pyjs, and long shot the (stalled) [Batavia](https://github.com/beeware/batavia).

**Comment by hiway** [comment]
@clach04 I haven't touched this code in years and don't seem to have original source/dir on current machine. Sorry, but I don't think I can be of much help here.
